import { availablePetsType, AnimalCategory } from "#utils/enums/animalType.js";
import type { Animal } from "../types/shopInterfaces.js";

export const ANIMAL_CONFIG: Record<availablePetsType, Animal> = {
  [availablePetsType.DOG]: {
    type: availablePetsType.DOG,
    category: AnimalCategory.DOMESTIC,
    defaultHunger: 100,
    defaultHappiness: 100,
    defaultHealth: 100,
  },
  [availablePetsType.CAT]: {
    type: availablePetsType.CAT,
    category: AnimalCategory.DOMESTIC,
    defaultHunger: 100,
    defaultHappiness: 100,
    defaultHealth: 100,
  },
  [availablePetsType.RABBIT]: {
    type: availablePetsType.RABBIT,
    category: AnimalCategory.SMALL,
    defaultHunger: 100,
    defaultHappiness: 100,
    defaultHealth: 100,
  },
  [availablePetsType.BIRD]: {
    type: availablePetsType.BIRD,
    category: AnimalCategory.BIRD,
    defaultHunger: 100,
    defaultHappiness: 100,
    defaultHealth: 100,
  },
  [availablePetsType.FISH]: {
    type: availablePetsType.FISH,
    category: AnimalCategory.WATER,
    defaultHunger: 100,
    defaultHappiness: 100,
    defaultHealth: 100,
  },
  [availablePetsType.HAMSTER]: {
    type: availablePetsType.HAMSTER,
    category: AnimalCategory.SMALL,
    defaultHunger: 100,
    defaultHappiness: 100,
    defaultHealth: 100,
  },
  [availablePetsType.TURTLE]: {
    type: availablePetsType.TURTLE,
    category: AnimalCategory.REPTILE,
    defaultHunger: 100,
    defaultHappiness: 100,
    defaultHealth: 100,
  },
  [availablePetsType.GUINEA_PIG]: {
    type: availablePetsType.GUINEA_PIG,
    category: AnimalCategory.SMALL,
    defaultHunger: 100,
    defaultHappiness: 100,
    defaultHealth: 100,
  },
  [availablePetsType.LIZARD]: {
    type: availablePetsType.LIZARD,
    category: AnimalCategory.REPTILE,
    defaultHunger: 100,
    defaultHappiness: 100,
    defaultHealth: 100,
  },
  [availablePetsType.SNAKE]: {
    type: availablePetsType.SNAKE,
    category: AnimalCategory.REPTILE,
    defaultHunger: 100,
    defaultHappiness: 100,
    defaultHealth: 100,
  },
  [availablePetsType.FROG]: {
    type: availablePetsType.FROG,
    category: AnimalCategory.REPTILE,
    defaultHunger: 100,
    defaultHappiness: 100,
    defaultHealth: 100,
  },
  [availablePetsType.PARROT]: {
    type: availablePetsType.PARROT,
    category: AnimalCategory.BIRD,
    defaultHunger: 100,
    defaultHappiness: 100,
    defaultHealth: 100,
  },
  [availablePetsType.FERRET]: {
    type: availablePetsType.FERRET,
    category: AnimalCategory.DOMESTIC,
    defaultHunger: 100,
    defaultHappiness: 100,
    defaultHealth: 100,
  },
  [availablePetsType.HEDGEHOG]: {
    type: availablePetsType.HEDGEHOG,
    category: AnimalCategory.SMALL,
    defaultHunger: 100,
    defaultHappiness: 100,
    defaultHealth: 100,
  },
  [availablePetsType.CINCHILLA]: {
    type: availablePetsType.CINCHILLA,
    category: AnimalCategory.SMALL,
    defaultHunger: 100,
    defaultHappiness: 100,
    defaultHealth: 100,
  },
};
