export enum MedicineCategory {
  GENERAL = "general",
  EYES = "eyes",
  EARS = "ears",
  SKIN = "skin",
  ENERGY = "energy",
  SPECIAL = "special",
}
export enum MedicineType {
  VITAMINS = "vitamins",
  ANTIBIOTICS = "antibiotics",
  PAINKILLERS = "painkillers",
  BANDAGES = "bandages",
  ANTISEPTIC = "antiseptic",
  EYE_DROPS = "eye_drops",
  EAR_DROPS = "ear_drops",
  COUGH_SYRUP = "cough_syrup",
  ALLERGY_PILLS = "allergy_pills",
  DIGESTIVE_AID = "digestive_aid",
  SKIN_OINTMENT = "skin_ointment",
  ANTI_INFLAMMATORY = "anti_inflammatory",
  HYDRATION_PACK = "hydration_pack",
  ENERGY_BOOST = "energy_boost",
  SPA_TREATMENT = "spa_treatment",
  VET_VISIT = "vet_visit",}