export enum ToyCategory {
  GENERAL = "general",
  DOMESTIC = "domestic",
  SMALL = "small",
  BIRD = "bird",
  WATER = "water",
  REPTILE = "reptile",
}
export enum ToyType {
  BALL = "ball",
  FRISBEE = "frisbee",
  CHEW_TOY = "chew_Toy",
  SQUEAKY_TOY = "squeaky_Toy",
  ROPE = "rope_toy",
  PLUSH = "plush_toy",
  PUZZLE = "puzzle_toy",
  TUG = "tug_toy",
  LASER = "interactive_laser",
  CATNIP = "catnip",
  FEATHER_WAND = "feather_wand",
  TUNNEL = "tunnel_toy",
  CLIMBING = "climbing_tree",
  SCRATCHING_POST = "scratching_post",
  BIRD_TOY = "bird_toy",
  SWING = "swing",
  MIRROR = "mirror",
  BUBBLE_MAKER = "bubble_maker",
  AQUARIUM_DECOR = "aquarium_decor",
  HEAT_ROCK = "heat_rock",
  CLIMBING_BRANCH = "climbing_branch",
  WHEEL = "exercise_wheel",
  CHEW_BLOCK = "chew_block",
}
